import React, { useEffect, useState } from 'react';
import { useSearchParams } from 'react-router-dom';

import { getMembers } from '../api/members';
import { PanelTable } from '../components/PanelTable';
import { useAuth } from '../auth/AuthContext';
import type { MemberPanel } from '../types';

/** Render the URL-backed, scoped search and filter member panel. */
export default function PanelPage(): React.JSX.Element {
  const { session, logout } = useAuth(); const [params, setParams] = useSearchParams(); const [panel, setPanel] = useState<MemberPanel | null>(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  const load = async (): Promise<void> => { if (!session) return; setLoading(true); setError(''); try { setPanel(await getMembers(session.access_token, params)); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to load members.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [session, params.toString()]);
  const update = (key: string, value: string): void => { const next = new URLSearchParams(params); value ? next.set(key, value) : next.delete(key); next.set('offset', '0'); setParams(next); };
  const onSort = (field: string): void => { const next = new URLSearchParams(params); const same = next.get('sort_by') === field; next.set('sort_by', field); next.set('sort_order', same && next.get('sort_order') === 'asc' ? 'desc' : 'asc'); setParams(next); };
  const offset = Number(params.get('offset') ?? '0'); const limit = Number(params.get('limit') ?? '10');
  return <main className="workspace"><header className="workspace-header"><div><p className="eyebrow">Care coordination</p><h1>Member panel</h1></div><button type="button" className="secondary-button" onClick={logout}>Sign out</button></header><section className="panel-controls" aria-label="Panel controls"><label>Search members<input value={params.get('query') ?? ''} onChange={(event) => update('query', event.target.value)} /></label><label>Risk<select value={params.get('risk_level') ?? ''} onChange={(event) => update('risk_level', event.target.value)}><option value="">All risk levels</option><option value="high">High</option><option value="moderate">Moderate</option></select></label><label>Plan<select value={params.get('plan') ?? ''} onChange={(event) => update('plan', event.target.value)}><option value="">All plans</option><option value="Meridian Advantage">Meridian Advantage</option><option value="Meridian Choice">Meridian Choice</option></select></label></section>{loading && <p className="state-message" aria-live="polite">Loading member panel…</p>}{error && <section className="state-message" role="alert"><p>We could not load members. {error}</p><button type="button" onClick={() => void load()}>Retry</button></section>}{!loading && !error && panel?.total === 0 && <section className="state-message"><p>No members are assigned to your panel.</p></section>}{!loading && !error && panel && panel.total > 0 && panel.items.length === 0 && <section className="state-message"><p>No members match these filters.</p><button type="button" onClick={() => setParams(new URLSearchParams())}>Clear filters</button></section>}{!loading && !error && panel && panel.items.length > 0 && <><PanelTable members={panel.items} sortBy={params.get('sort_by') ?? 'last_name'} sortOrder={params.get('sort_order') ?? 'asc'} onSort={onSort} /><nav className="pagination" aria-label="Panel pagination"><button type="button" disabled={offset === 0} onClick={() => update('offset', String(Math.max(0, offset - limit)))}>Previous</button><span>{offset + 1}–{Math.min(offset + limit, panel.total)} of {panel.total}</span><button type="button" disabled={offset + limit >= panel.total} onClick={() => update('offset', String(offset + limit))}>Next</button></nav></>}</main>;
}